### PR TITLE
Update citation file with JOSS paper

### PR DESCRIPTION
**Pull request by crnh**
## Proposed change

Update CITATION.cff because the JOSS paper has just been published.

## Type of change

- [ ] Example (a notebook demonstrating how to use ZOSPy for a specific application)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New analysis (a wrapper around an OpticStudio analysis)
- [ ] New feature (other than an analysis)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Documentation (improvement of either the docstrings or the documentation website)

# Additional information

- Python version: ...
- OpticStudio version: ...

## Checklist

- [ ] I have followed the [contribution guidelines][contribution-guidelines]
- [ ] The code has been linted, formatted and tested locally using tox.
- [ ] Local tests pass. **Please fix any problems before opening a PR. If this is not possible, specify what doesn't work and why you can't fix it.**
- [ ] I added new tests for any features contributed, or updated existing tests.
- [ ] I updated CHANGELOG.md with my changes (except for refactorings and changes in the documentation).

If you contributed an analysis:

- [ ] I did not use `AttrDict`s for the analysis result data (please use dataclasses instead).

If you contributed an example:

- [ ] I contributed my example as a Jupyter notebook.
    

[contribution-guidelines]: https://github.com/MREYE-LUMC/ZOSPy/blob/main/CONTRIBUTING.md
[unittest-instructions]: https://github.com/MREYE-LUMC/ZOSPy/blob/main/tests/README.md
[numpydoc]: https://numpydoc.readthedocs.io/en/latest/format.html

### CODE REVIEW

**Comment by jwmbeenakker** [comment]
Wouldn't you also want to remove `doi: 10.5281/zenodo.10805414` from the citation file?

**Review by jwmbeenakker — CHANGES_REQUESTED** [review]
I would suggest to use this pull request to update the citation preferences throughout ZOSPy. in particularly:
- [x] the referencing section on the readme
- [x] the documentation of the examples
  - [x] mention the general citation of the JOSS paper for ZOSPy
  - [x] per example the paper to which it belongs (eg. the Escudero paper for the eye model)
- [x] A short link to the JOSS paper in the about section
- [ ] The simple example references the JOSS paper, but the link is broken

**Comment by crnh** [comment]
> Wouldn't you also want to remove doi: 10.5281/zenodo.10805414 from the citation file?

This is the citation file recommended by JOSS, so they recommend to include the Zenodo DOI

**Comment by jwmbeenakker** [comment]
> This is the citation file recommended by JOSS, so they recommend to include the Zenodo DOI

Hmm, I understand it from their point of view (referencing to the version they evaluated), but for general referencing to ZOSPy I would consider it undesirable as 1) the Zenodo DOI is linked to single version of ZOSPy 2) if people want to directly refer to the code, I would find a reference to the GitHub repository more appropriate

**Review by jwmbeenakker — COMMENTED** [review]
- Citation.cff looks good.
- README looks good as well. Is the used zenodo doi linking to the latest package version (that would be my preference, as people generally don't update their reference manager after first inclusion)
-

**Comment by crnh** [comment]
I suppose you mean the Zenodo DOI in the badge; that badge automatically links to the latest Zenodo entry. The DOI in the badge is thus automatically updated.

**Review by jwmbeenakker — APPROVED** [review]

**Pull request merged**
