### PR TITLE
Synchronize with LUMC GitLab

### LINKED ISSUE #31: UnicodeDecodeErrors when parsing analysis text output
This problem was discovered while running the unit tests using OpticStudio 23R2. Basically all analyses that use text-based output fail.

_Originally posted by @Omnistic in https://github.com/MREYE-LUMC/ZOSPy/issues/30#issuecomment-1651612691_

### PR DESCRIPTION
**Pull request by crnh**
## Proposed change

Apply changes from LUMC GitLab:
### Fixed
- Erroneous parsing of analyses results when textfile encoding was not set to `Unicode` by implementing `zospy.zpcore.ZOS.get_txt_file_encoding` (!36)

### Changed
- Updated how and when constants in `zospy.api.config` are determined for more clarity (!39)

## Type of change

- [ ] Example (a notebook demonstrating how to use ZOSPy for a specific application)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New analysis (a wrapper around an OpticStudio analysis)
- [ ] New feature (other than an analysis)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

# Additional information

- Python version: N/A
- OpticStudio version: N/A

## Related issues

Closes #31

## Checklist

- [x] I have followed the [contribution guidelines][contribution-guidelines]
- [x] The code has been linted, formatted and tested locally using tox.
- [x] Local tests pass. **Please fix any problems before opening a PR. If this is not possible, specify what doesn't work and why you can't fix it.**
- [x] I added new tests for any features contributed, or updated existing tests.
- [x] I updated CHANGELOG.md with my changes (except for refactorings and changes in the documentation).

If you contributed an analysis:

- [ ] I did not use `AttrDict`s for the analysis result data (please use dataclasses instead).

If you contributed an example:

- [ ] I contributed my example as a Jupyter notebook.
    

[contribution-guidelines]: https://github.com/MREYE-LUMC/ZOSPy/blob/main/CONTRIBUTING.md
[unittest-instructions]: https://github.com/MREYE-LUMC/ZOSPy/blob/main/tests/README.md
[numpydoc]: https://numpydoc.readthedocs.io/en/latest/format.html

### CODE REVIEW

**Comment by LucVV** [comment]
It seems that the compatibility information for version 23.2.1 has been dropped in the process

**Comment by crnh** [comment]
The compatibility problems have been fixed!

**Review by LucVV — APPROVED** [review]
All unit tests pass!

**Review by jwmbeenakker — DISMISSED** [review]
Maybe specify the changes that retrieved from the local LUMC gitlab under "proposed change"

**Pull request merged**
