### PR TITLE
New-style Rays and Spots analyses

### PR DESCRIPTION
**Pull request by crnh**
## Proposed change

New-style analyses for the Ray Fan analysis. 

Please comment on the current result structure: is this acceptable or should we return a single DataFrame?
Keeping the old structure is in any case unacceptable, because it contained strings like `Tangential fan, field number 1 = 30,00 (deg)`, which depend on the locale.

## Type of change

- [ ] Example (a notebook demonstrating how to use ZOSPy for a specific application)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New analysis (a wrapper around an OpticStudio analysis)
- [ ] New feature (other than an analysis)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Documentation (improvement of either the docstrings or the documentation website)

# Additional information

- Python version: 3.9-3.12
- OpticStudio version: 24R1

## Checklist

- [x] I have followed the [contribution guidelines][contribution-guidelines]
- [x] The code has been linted, formatted and tested locally using tox.
- [x] Local tests pass. **Please fix any problems before opening a PR. If this is not possible, specify what doesn't work and why you can't fix it.**
- [x] I added new tests for any features contributed, or updated existing tests.
- [ ] I updated CHANGELOG.md with my changes (except for refactorings and changes in the documentation).

If you contributed an analysis:

- [ ] I did not use `AttrDict`s for the analysis result data (please use dataclasses instead).

If you contributed an example:

- [ ] I contributed my example as a Jupyter notebook.
    

[contribution-guidelines]: https://github.com/MREYE-LUMC/ZOSPy/blob/main/CONTRIBUTING.md
[unittest-instructions]: https://github.com/MREYE-LUMC/ZOSPy/blob/main/tests/README.md
[numpydoc]: https://numpydoc.readthedocs.io/en/latest/format.html

### CODE REVIEW

**Comment by jwmbeenakker** [comment]
Can you post an example/dump of the proposed results structure? (is a bit hard to evaluate without optic studio on my local pc)

**Comment by crnh** [comment]
Here is some example data:

<details>
<summary>Click to reveal</summary>

```
Surface: Image (retina )
Units are µm.
Aberration data is measured in image plane local coordinates.
Tangential data is y aberration as a function of Py.
Sagittal data is x aberration as a function of Px.

Tangential fan, field number 1 = 0,0000 (deg)

  Pupil    	     0,543000    	 0,553000
 -1,000  	     0,208965  	     0,208965
 -0,950  	     0,119676  	     0,119676
 -0,900  	     0,039890  	     0,039890
 -0,850  	    -0,030163  	    -0,030163
 -0,800  	    -0,090386  	    -0,090386
 -0,750  	    -0,140804  	    -0,140804
 -0,700  	    -0,181554  	    -0,181554
 -0,650  	    -0,212873  	    -0,212873
 -0,600  	    -0,235088  	    -0,235088
 -0,550  	    -0,248609  	    -0,248609
 -0,500  	    -0,253918  	    -0,253918
 -0,450  	    -0,251567  	    -0,251567
 -0,400  	    -0,242161  	    -0,242161
 -0,350  	    -0,226361  	    -0,226361
 -0,300  	    -0,204870  	    -0,204870
 -0,250  	    -0,178431  	    -0,178431
 -0,200  	    -0,147821  	    -0,147821
 -0,150  	    -0,113842  	    -0,113842
 -0,100  	    -0,077317  	    -0,077317
 -0,050  	    -0,039086  	    -0,039086
  0,000  	    -0,000000  	    -0,000000
  0,050  	     0,039086  	     0,039086
  0,100  	     0,077317  	     0,077317
  0,150  	     0,113842  	     0,113842
  0,200  	     0,147821  	     0,147821
  0,250  	     0,178431  	     0,178431
  0,300  	     0,204870  	     0,204870
  0,350  	     0,226361  	     0,226361
  0,400  	     0,242161  	     0,242161
  0,450  	     0,251567  	     0,251567
  0,500  	     0,253918  	     0,253918
  0,550  	     0,248609  	     0,248609
  0,600  	     0,235088  	     0,235088
  0,650  	     0,212873  	     0,212873
  0,700  	     0,181554  	     0,181554
  0,750  	     0,140804  	     0,140804
  0,800  	     0,090386  	     0,090386
  0,850  	     0,030163  	     0,030163
  0,900  	    -0,039890  	    -0,039890
  0,950  	    -0,119676  	    -0,119676
  1,000  	    -0,208965  	    -0,208965

Sagittal fan, field number 1 = 0,0000 (deg)

  Pupil    	     0,543000    	 0,553000
 -1,000  	     0,208965  	     0,208965
 -0,950  	     0,119676  	     0,119676
 -0,900  	     0,039890  	     0,039890
 -0,850  	    -0,030163  	    -0,030163
 -0,800  	    -0,090386  	    -0,090386
 -0,750  	    -0,140804  	    -0,140804
 -0,700  	    -0,181554  	    -0,181554
 -0,650  	    -0,212873  	    -0,212873
 -0,600  	    -0,235088  	    -0,235088
 -0,550  	    -0,248609  	    -0,248609
 -0,500  	    -0,253918  	    -0,253918
 -0,450  	    -0,251567  	    -0,251567
 -0,400  	    -0,242161  	    -0,242161
 -0,350  	    -0,226361  	    -0,226361
 -0,300  	    -0,204870  	    -0,204870
 -0,250  	    -0,178431  	    -0,178431
 -0,200  	    -0,147821  	    -0,147821
 -0,150  	    -0,113842  	    -0,113842
 -0,100  	    -0,077317  	    -0,077317
 -0,050  	    -0,039086  	    -0,039086
  0,000  	    -0,000000  	    -0,000000
  0,050  	     0,039086  	     0,039086
  0,100  	     0,077317  	     0,077317
  0,150  	     0,113842  	     0,113842
  0,200  	     0,147821  	     0,147821
  0,250  	     0,178431  	     0,178431
  0,300  	     0,204870  	     0,204870
  0,350  	     0,226361  	     0,226361
  0,400  	     0,242161  	     0,242161
  0,450  	     0,251567  	     0,251567
  0,500  	     0,253918  	     0,253918
  0,550  	     0,248609  	     0,248609
  0,600  	     0,235088  	     0,235088
  0,650  	     0,212873  	     0,212873
  0,700  	     0,181554  	     0,181554
  0,750  	     0,140804  	     0,140804
  0,800  	     0,090386  	     0,090386
  0,850  	     0,030163  	     0,030163
  0,900  	    -0,039890  	    -0,039890
  0,950  	    -0,119676  	    -0,119676
  1,000  	    -0,208965  	    -0,208965

Tangential fan, field number 2 = 0,0000 (deg)

  Pupil    	     0,543000    	 0,553000
 -1,000  	     0,208965  	     0,208965
 -0,950  	     0,119676  	     0,119676
 -0,900  	     0,039890  	     0,039890
 -0,850  	    -0,030163  	    -0,030163
 -0,800  	    -0,090386  	    -0,090386
 -0,750  	    -0,140804  	    -0,140804
 -0,700  	    -0,181554  	    -0,181554
 -0,650  	    -0,212873  	    -0,212873
 -0,600  	    -0,235088  	    -0,235088
 -0,550  	    -0,248609  	    -0,248609
 -0,500  	    -0,253918  	    -0,253918
 -0,450  	    -0,251567  	    -0,251567
 -0,400  	    -0,242161  	    -0,242161
 -0,350  	    -0,226361  	    -0,226361
 -0,300  	    -0,204870  	    -0,204870
 -0,250  	    -0,178431  	    -0,178431
 -0,200  	    -0,147821  	    -0,147821
 -0,150  	    -0,113842  	    -0,113842
 -0,100  	    -0,077317  	    -0,077317
 -0,050  	    -0,039086  	    -0,039086
  0,000  	    -0,000000  	    -0,000000
  0,050  	     0,039086  	     0,039086
  0,100  	     0,077317  	     0,077317
  0,150  	     0,113842  	     0,113842
  0,200  	     0,147821  	     0,147821
  0,250  	     0,178431  	     0,178431
  0,300  	     0,204870  	     0,204870
  0,350  	     0,226361  	     0,226361
  0,400  	     0,242161  	     0,242161
  0,450  	     0,251567  	     0,251567
  0,500  	     0,253918  	     0,253918
  0,550  	     0,248609  	     0,248609
  0,600  	     0,235088  	     0,235088
  0,650  	     0,212873  	     0,212873
  0,700  	     0,181554  	     0,181554
  0,750  	     0,140804  	     0,140804
  0,800  	     0,090386  	     0,090386
  0,850  	     0,030163  	     0,030163
  0,900  	    -0,039890  	    -0,039890
  0,950  	    -0,119676  	    -0,119676
  1,000  	    -0,208965  	    -0,208965

Sagittal fan, field number 2 = 0,0000 (deg)

  Pupil    	     0,543000    	 0,553000
 -1,000  	     0,208965  	     0,208965
 -0,950  	     0,119676  	     0,119676
 -0,900  	     0,039890  	     0,039890
 -0,850  	    -0,030163  	    -0,030163
 -0,800  	    -0,090386  	    -0,090386
 -0,750  	    -0,140804  	    -0,140804
 -0,700  	    -0,181554  	    -0,181554
 -0,650  	    -0,212873  	    -0,212873
 -0,600  	    -0,235088  	    -0,235088
 -0,550  	    -0,248609  	    -0,248609
 -0,500  	    -0,253918  	    -0,253918
 -0,450  	    -0,251567  	    -0,251567
 -0,400  	    -0,242161  	    -0,242161
 -0,350  	    -0,226361  	    -0,226361
 -0,300  	    -0,204870  	    -0,204870
 -0,250  	    -0,178431  	    -0,178431
 -0,200  	    -0,147821  	    -0,147821
 -0,150  	    -0,113842  	    -0,113842
 -0,100  	    -0,077317  	    -0,077317
 -0,050  	    -0,039086  	    -0,039086
  0,000  	    -0,000000  	    -0,000000
  0,050  	     0,039086  	     0,039086
  0,100  	     0,077317  	     0,077317
  0,150  	     0,113842  	     0,113842
  0,200  	     0,147821  	     0,147821
  0,250  	     0,178431  	     0,178431
  0,300  	     0,204870  	     0,204870
  0,350  	     0,226361  	     0,226361
  0,400  	     0,242161  	     0,242161
  0,450  	     0,251567  	     0,251567
  0,500  	     0,253918  	     0,253918
  0,550  	     0,248609  	     0,248609
  0,600  	     0,235088  	     0,235088
  0,650  	     0,212873  	     0,212873
  0,700  	     0,181554  	     0,181554
  0,750  	     0,140804  	     0,140804
  0,800  	     0,090386  	     0,090386
  0,850  	     0,030163  	     0,030163
  0,900  	    -0,039890  	    -0,039890
  0,950  	    -0,119676  	    -0,119676
  1,000  	    -0,208965  	    -0,208965
```

</details>

And the proposed result structure can be found here: https://github.com/MREYE-LUMC/ZOSPy/blob/187596447827cacd8690a9b59e438b49b2892b07/zospy/analyses/new/raysandspots/ray_fan.py#L31
That's likely to be more insightful than a JSON dump, due to the presence of e.g. serialized dataframes.

**Comment by LucVV** [comment]
The current structure seems fine to me. I think the alternative of list of `RayFan`s might make it less user friendly, as you have to look through the list to find out where the tangential result is. I am however not opposed to a single dataframe, as it keeps the data together but also allows what the current implementation does, e.g.:

```python
data = pd.DataFrame(columns=['Tangential', 'Sagittal'])

data.Tangential
``` 

is fine in Pandas. It furthermore gives the convenience of directly plotting both using `DataFrame.plot`.

**Comment by LucVV** [comment]
Ah yes, in that case, the current implementation seems the best. One other way that I can imagine is to concatenate the dataframes of e.g. all tangential analyses. However, then you can have either the field coordinate or the flied number as columns (and ideally, you want to have both as an option for your search). So I think that the current method is the optimal one. If wanted, we can always add a `to_multiindex_dataframe()` in the future.

**Comment by crnh** [comment]
I added a `to_dataframe` method to `RayFanResult`, so the data can be easily converted to a long-format dataframe, e.g.

```
    Pupil   Direction  Field Number  Field     0.543
0    -1.0  Tangential             1    0.0  2.041610
1    -0.9  Tangential             1    0.0  1.145762
2    -0.8  Tangential             1    0.0  0.469759
3    -0.7  Tangential             1    0.0 -0.011617
4    -0.6  Tangential             1    0.0 -0.323302
5    -0.5  Tangential             1    0.0 -0.489989
6    -0.4  Tangential             1    0.0 -0.536159
7    -0.3  Tangential             1    0.0 -0.486121
8    -0.2  Tangential             1    0.0 -0.364047
9    -0.1  Tangential             1    0.0 -0.194007
10    0.0  Tangential             1    0.0 -0.000000
11    0.1  Tangential             1    0.0  0.194007
12    0.2  Tangential             1    0.0  0.364047
13    0.3  Tangential             1    0.0  0.486121
14    0.4  Tangential             1    0.0  0.536159
15    0.5  Tangential             1    0.0  0.489989
16    0.6  Tangential             1    0.0  0.323302
17    0.7  Tangential             1    0.0  0.011617
18    0.8  Tangential             1    0.0 -0.469759
19    0.9  Tangential             1    0.0 -1.145762
20    1.0  Tangential             1    0.0 -2.041610
21   -1.0    Sagittal             1    0.0  2.041610
22   -0.9    Sagittal             1    0.0  1.145762
23   -0.8    Sagittal             1    0.0  0.469759
24   -0.7    Sagittal             1    0.0 -0.011617
25   -0.6    Sagittal             1    0.0 -0.323302
26   -0.5    Sagittal             1    0.0 -0.489989
27   -0.4    Sagittal             1    0.0 -0.536159
28   -0.3    Sagittal             1    0.0 -0.486121
29   -0.2    Sagittal             1    0.0 -0.364047
30   -0.1    Sagittal             1    0.0 -0.194007
31    0.0    Sagittal             1    0.0 -0.000000
32    0.1    Sagittal             1    0.0  0.194007
33    0.2    Sagittal             1    0.0  0.364047
34    0.3    Sagittal             1    0.0  0.486121
35    0.4    Sagittal             1    0.0  0.536159
36    0.5    Sagittal             1    0.0  0.489989
37    0.6    Sagittal             1    0.0  0.323302
38    0.7    Sagittal             1    0.0  0.011617
39    0.8    Sagittal             1    0.0 -0.469759
40    0.9    Sagittal             1    0.0 -1.145762
41    1.0    Sagittal             1    0.0 -2.041610
```

**Comment by LucVV** [comment]
this is neat! The only thing that is a bit confusing is the `0.543` in the header, but that is how OpticStudio reports the results. For clarity, we could change it to `Wavelength:0.543`, but then again, it is more on the OpticStudio side, so I am not sure. Otherwise, this analysis is good to go for me! It works perfectly fine!

**Review by LucVV — APPROVED** [review]

**Comment by crnh** [comment]
> The only thing that is a bit confusing is the `0.543` in the header

We can move the wavelength to a separate column as well. I don't know how Pandas' plotting module handles that, but for plotting with Seaborn it would be perfect.

**Comment by LucVV** [comment]
> We can move the wavelength to a separate column as well. I don't know how Pandas' plotting module handles that, but for plotting with Seaborn it would be perfect.

 I think that would be great to implement in `to_dataframe` yes!

**Comment by crnh** [comment]
The dataframe now contains the wavelength as a separate column, e.g.

```
    Pupil   Direction  Field Number  Field  Wavelength  Aberration
0    -1.0  Tangential             1    0.0       0.543    2.041610
1    -1.0  Tangential             1    0.0       0.555    2.041610
2    -0.9  Tangential             1    0.0       0.543    1.145762
3    -0.9  Tangential             1    0.0       0.555    1.145762
4    -0.8  Tangential             1    0.0       0.543    0.469759
..    ...         ...           ...    ...         ...         ...
79    0.8    Sagittal             1    0.0       0.555   -0.469759
80    0.9    Sagittal             1    0.0       0.543   -1.145762
81    0.9    Sagittal             1    0.0       0.555   -1.145762
82    1.0    Sagittal             1    0.0       0.543   -2.041610
83    1.0    Sagittal             1    0.0       0.555   -2.041610
```

@LucVV I named the data column 'Aberration', do you agree with that or do you know a better name for it?

Also, I discovered the current implementation can't handle fields with 2D coordinates, so I'll add support for those as well.

**Comment by crnh** [comment]
> Also, I discovered the current implementation can't handle fields with 2D coordinates, so I'll add support for those as well.

Support for this has been added!

**Pull request merged**
